### ISSUE TITLE
Localization is needed

### ISSUE THREAD

**Issue by lewadedun** [matrixx/TrulyYours#3]
Can you start using the Transifex?
And I sent you a file with translation into Russian )

**Comment by matrixx** [comment]
I started a Transifex project for the app: https://www.transifex.com/projects/p/trulyyours/
You can either tell me your Transifex account id or send the file by email :)

**Comment by lewadedun** [comment]
You have already added me in Russia team ))

**Comment by matrixx** [comment]
Thanks for the translation! :)

**Comment by lewadedun** [comment]
you're welcome ; )
